sudo: required
dist: bionic
language: cpp

compiler:
  - gcc

notifications:
  email:
    on_success: never
    on_failure: always

script:
  - ${TRAVIS_BUILD_DIR}
  - cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=ON ..
  - cmake --build .
  - ctest --output-on-failure --verbose